services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npx tsc && node dist/app.js"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data:
